name: "Release CN version"

on:
  push:
    tags:
      - v1*

jobs:
  release-cn:
    name: release-cn
    runs-on: ubuntu-20.04

    steps:
      ################################################################
      # Git checkout
      - name: Checkout repository
        uses: actions/checkout@v2

      ################################################################
      # Build
      # The github.ref is, for example, refs/tags/v1.0.52
      # Generate variables like:
      #   SRS_TAG=v1.0.52
      #   SRS_MAJOR=1
      # @see https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable
      - name: Generate varaiables
        run: |
          SRS_TAG=$(echo ${{ github.ref }}| awk -F '/' '{print $3}')
          echo "SRS_TAG=$SRS_TAG" >> $GITHUB_ENV
          SRS_MAJOR=$(echo $SRS_TAG| cut -c 2)
          echo "SRS_MAJOR=$SRS_MAJOR" >> $GITHUB_ENV

      # Build SRS image
      - name: Build SRS docker image
        run: |
          echo "Release ossrs/docs:cn-$SRS_TAG"
          docker build --tag ossrs/docs:cn-$SRS_TAG --build-arg SEARCH_APIKEY=${{ secrets.SEARCH_APIKEY }} \
            -f Dockerfile.cn .

      ################################################################
      # Docker
      - name: Login docker hub
        uses: docker/login-action@v1
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"

      - name: Push to docker hub
        run: |
          docker tag ossrs/docs:cn-$SRS_TAG ossrs/docs:cn-$SRS_MAJOR
          docker push --all-tags ossrs/docs

      ################################################################
      # Aliyun ACR
      - name: Login Aliyun docker hub
        uses: aliyun/acr-login@v1
        with:
          login-server: https://registry.cn-hangzhou.aliyuncs.com
          username: "${{ secrets.ACR_USERNAME }}"
          password: "${{ secrets.ACR_PASSWORD }}"

      - name: Push to Aliyun docker hub
        run: |
          docker tag ossrs/docs:cn-$SRS_TAG registry.cn-hangzhou.aliyuncs.com/ossrs/docs:cn-$SRS_TAG
          docker tag ossrs/docs:cn-$SRS_TAG registry.cn-hangzhou.aliyuncs.com/ossrs/docs:cn-$SRS_MAJOR
          docker push --all-tags registry.cn-hangzhou.aliyuncs.com/ossrs/docs

      ################################################################
      # K8S
      - name: Setup KUBCONFIG for Aliyun ACK
        run: |-
          KUBECONFIG=$RUNNER_TEMP/kubeconfig_$(date +%s)
          echo "${{ secrets.KUBCONFIG }}" > $KUBECONFIG
          echo "KUBECONFIG=$KUBECONFIG" >> $GITHUB_ENV

      # Update config from search/scraper.json
      - name: Update config from search/scraper.json
        run: |-
          cp search/scraper.json srs-docs-search-config.json
          sed -i 's|.*url.*host.docker.internal:3000.*|      "url": "http://docs-tcp-service:80/lts/",|g' srs-docs-search-config.json
          sed -i 's|host.docker.internal|docs-tcp-service|g' srs-docs-search-config.json
          kubectl create configmap srs-docs --from-file srs-docs-search-config.json -o yaml --dry-run=client | kubectl apply -f -
          kubectl describe configmap/srs-docs

      # Restart the typesense and scraper
      - name: Restart the typesense and scraper
        run: |-
          kubectl delete pods -l app=typesense --grace-period=0 --force

      # K8S for SRS web
      - name: Release SRS web to Aliyun ACK
        run: |-
          kubectl set image deploy/docs-deploy docs=registry.cn-hangzhou.aliyuncs.com/ossrs/docs:cn-$SRS_TAG
          kubectl describe deploy/docs-deploy
